// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"Sportify/internal/db"
)

func NoviOglas(korisnik *db.Korisnik, sportovi []db.Sport, lokacije []db.Lokacija, sportSablon *db.Sport) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form class=\"grid grid-cols-3 gap-5 font-bold font-mono\" hx-post=\"/api/dodajOglas\" hx-swap=\"none\"><div class=\"col-span-2 px-5 py-15\"><div class=\"\"><div class=\"w-full aspect-video border border-red-600\" id=\"map\" data-center=\"[43.3180, 21.8940]\" data-zoom=\"20\"><div data-tile=\"EsriWorldImagery\"></div><div data-tile=\"OpenStreetMap\" data-default-tile></div><span class=\"custom-control zoom-level\" id=\"zoom-level\"></span><div data-hyperleaflet-source id=\"mapa-podaci\"><input name=\"novi-oglas-koordinate\" id=\"novi-oglas-koordinate\" class=\"hidden\"></div></div><div class=\"relative bg-white w-6/7 mt-8 p-5 shadow-md\"><div class=\"absolute top-0 left-0 w-40 h-2 bg-red-600 -translate-y-1/2 translate-x-1/3 -skew-x-12\"></div><div class=\"text-gray-400 font-light uppercase mb-4\">opis</div><textarea placeholder=\"Dodajte opis...\" id=\"opis-input\" name=\"novi-oglas-opis\" class=\"w-full bg-white shadow-md border border-gray-400 rounded-xl p-3 mt-5 resize-none\"></textarea></div></div></div><div class=\"col-span-1 py-15\"><div class=\"bg-(--crna) p-5 pb-15\"><div class=\"text-white text-3xl font-bold uppercase py-5\">podaci</div><div class=\"border-t-2 border-red-600 mt-2 py-3 flex flex-row flex-nowrap\"><div class=\"flex flex-col flex-nowrap justify-start\"><div class=\"bg-red-600 aspect-square w-10 flex justify-center items-center\"><span class=\"text-white text-xl\">1</span></div></div><div class=\"flex flex-col flex-nowrap ms-3 text-white w-full\"><div class=\"uppercase text-gray-400\">sport</div><select name=\"novi-oglas-sport\" id=\"novi-oglas-sport\" required class=\"w-full border border-red-600 rounded-xl p-2 my-2 text-white bg-black hover:cursor-pointer\"><option hidden disabled selected value class=\"uppercase\">Izaberite sport</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, sport := range sportovi {
				if sportSablon != nil && sportSablon.Naziv == sport.Naziv {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<option selected value=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var3 string
					templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(sport.Naziv)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 49, Col: 46}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"uppercase\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var4 string
					templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(sport.Naziv)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 49, Col: 80}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</option>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<option value=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(sport.Naziv)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 51, Col: 37}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\" class=\"uppercase\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(sport.Naziv)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 51, Col: 71}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</option>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</select></div></div><div class=\"border-t-2 border-red-600 py-3 flex flex-row flex-nowrap\"><div class=\"flex flex-col flex-nowrap justify-start\"><div class=\"bg-red-600 aspect-square w-10 flex justify-center items-center\"><span class=\"text-white text-xl\">2</span></div></div><div class=\"flex flex-col flex-nowrap ms-3 text-white w-full\"><div class=\"uppercase text-gray-400\">mesto</div><select name=\"novi-oglas-mesto\" id=\"novi-oglas-mesto\" required class=\"w-full border border-red-600 rounded-xl p-2 my-2 text-white bg-black hover:cursor-pointer\"><option hidden disabled selected value class=\"uppercase\">Izaberite lokaciju</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			for _, lokacija := range lokacije {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<option value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(lokacija.Mesto)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 70, Col: 39}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" class=\"uppercase\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(lokacija.Mesto)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 70, Col: 76}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</option>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</select></div></div><div class=\"border-t-2 border-red-600 py-3 flex flex-row flex-nowrap\"><div class=\"flex flex-col flex-nowrap justify-start\"><div class=\"bg-red-600 aspect-square w-10 flex justify-center items-center\"><span class=\"text-white text-xl\">3</span></div></div><div class=\"flex flex-col flex-nowrap ms-3 text-white w-full\"><div class=\"uppercase text-gray-400\">datum</div><input required type=\"date\" id=\"novi-oglas-datum\" name=\"novi-oglas-datum\" class=\"dark:[color-scheme:dark] border border-red-600 rounded-xl p-2 bg-black hover:cursor-pointer\"></div></div><div class=\"border-y-2 border-red-600 py-3 flex flex-row flex-nowrap\"><div class=\"flex flex-col flex-nowrap justify-start\"><div class=\"bg-red-600 aspect-square w-10 flex justify-center items-center\"><span class=\"text-white text-xl\">4</span></div></div><div class=\"flex flex-col flex-nowrap ms-3 text-white w-full\"><div class=\"uppercase text-gray-400\">vreme</div><input required type=\"time\" id=\"novi-oglas-vreme\" name=\"novi-oglas-vreme\" class=\"dark:[color-scheme:dark] border border-red-600 rounded-xl p-2 bg-black hover:cursor-pointer\"></div></div><div class=\"border-b-2 border-red-600 py-3 flex flex-row flex-nowrap\"><div class=\"flex flex-col flex-nowrap justify-start\"><div class=\"bg-red-600 aspect-square w-10 flex justify-center items-center\"><span class=\"text-white text-xl\">5</span></div></div><div class=\"flex flex-col flex-nowrap ms-3 text-white w-full\"><div class=\"uppercase text-gray-400\">potrebno igrača</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sportSablon != nil {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<input required type=\"number\" name=\"novi-oglas-potrebno-igraca\" id=\"novi-oglas-potrebno-igraca\" min=\"1\" max=\"99\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(sportSablon.PotrebnoIgraca)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `noviOglas.templ`, Line: 112, Col: 43}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" step=\"1\" class=\"dark:[color-scheme:dark] border border-red-600 rounded-xl p-2 bg-black\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<input required type=\"number\" name=\"novi-oglas-potrebno-igraca\" id=\"novi-oglas-potrebno-igraca\" min=\"1\" max=\"99\" value=\"1\" step=\"1\" class=\"dark:[color-scheme:dark] border border-red-600 rounded-xl p-2 bg-black\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></div><button type=\"submit\" class=\"uppercase bg-red-600 w-full py-4 mt-12 rounded-lg text-white text-xl \n\t\t\t\t\t\t\t\t\t\thover:cursor-pointer hover:bg-red-700 transition-all duration-300\">Napravi</button></div></div></form><script src=\"/static/skripte/noviOglas.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Raspored(korisnik).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
